[package]
name = "tree-sitter-jsdn"
description = "JSDN (JavaScript Data Notation) is a heavyweight data-interchange format."
version = "0.1.0"
authors = ["Dominic Tassio"]
license = "MIT"
readme = "README.md"
keywords = ["incremental", "parsing", "tree-sitter", "jsdn"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/dominictassio/jsdn"
edition = "2021"
autoexamples = false

build = "bindings/rust/build.rs"
include = ["bindings/rust/*", "grammar.js", "queries/*", "src/*"]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language = "0.1"

[build-dependencies]
cc = "1.1.22"

[dev-dependencies]
tree-sitter = "0.24.3"
